eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.tttt.danang.gov.vn:8061/eureka
info:
  component: Sở giao thông vận tải Service
logging:
  level:
    ROOT: ERROR
    org:
      hibernate:
        type: trace
      springframework:
        web: ERROR
    vn:
      dnict: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} -%5p %m%n'
security:
  token:
    endpoint: http://103.101.76.123:8000/auth/uaa/user
    header: X-Token
server:
  port: 8193
  connection-timeout: 1000000
spring:
  cloud:
    refresh:
      enabled: false
  datasource:
    password: Dnict@999
    testWhileIdle: true
    url: jdbc:postgresql://localhost:5432/sgtvt_csdl_chuyennganh
    username: postgres
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB